// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Muhammad Farras Fajri",
            "url": "https://github.com/muhammadfarrasfajri"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "Autentikasi user menggunakan IdToken dari Google. Jika berhasil, akan mengembalikan Access Token dan Refresh Token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login with Google",
                "parameters": [
                    {
                        "description": "Google ID Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login Berhasil",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Format data salah",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Token Google tidak valid",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengeluarkan user dari sesi dengan membatalkan (invalidate) Refresh Token yang dikirim di body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout User",
                "parameters": [
                    {
                        "description": "Kirimkan Refresh Token yang ingin di-logout",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RefreshTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Logout Berhasil",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Format data salah",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal memproses logout di server",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/refresh-token": {
            "post": {
                "description": "Mendapatkan Access Token baru menggunakan Refresh Token yang valid.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh Access Token",
                "parameters": [
                    {
                        "description": "Kirimkan Refresh Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RefreshTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token Berhasil Diperbarui",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Format data salah",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Refresh Token tidak valid atau expired",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register/beneficiary": {
            "post": {
                "description": "Mendaftarkan user sebagai Penerima Manfaat (Beneficiary) dengan data profil lengkap menggunakan Google IdToken.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register Beneficiary with Google",
                "parameters": [
                    {
                        "description": "Data User dan Profil Beneficiary",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RegisterBeneficiaryReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Berhasil mendaftar sebagai beneficiary",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Data tidak lengkap atau format salah",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register/donor": {
            "post": {
                "description": "Mendaftarkan user baru sebagai donor menggunakan IdToken dari Google Auth.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register Donor with Google",
                "parameters": [
                    {
                        "description": "Kirimkan IdToken dari Google",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Register Berhasil",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Data tidak valid atau Token kosong",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/campaign": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Membuat penggalangan dana baru. Membutuhkan login sebagai Beneficiary dan upload gambar banner.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Campaign"
                ],
                "summary": "Create New Campaign",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Judul Kampanye",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deskripsi Lengkap",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Target Dana (Rp)",
                        "name": "target_amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenggat Waktu (YYYY-MM-DD)",
                        "name": "deadline",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID Kategori",
                        "name": "campaign_category_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Gambar Banner Kampanye",
                        "name": "image_banner",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Kampanye Berhasil Dibuat",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Input tidak valid",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/campaign/active": {
            "get": {
                "description": "Mengambil daftar semua kampanye yang berstatus 'active'. Digunakan oleh donatur untuk melihat daftar donasi yang tersedia.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Campaign"
                ],
                "summary": "Get Active Campaigns",
                "responses": {
                    "200": {
                        "description": "Daftar kampanye aktif",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Campaign"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Gagal mengambil data dari database",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/campaign/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil semua daftar kampanye yang dibuat oleh user (Beneficiary) yang sedang login berdasarkan token JWT.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Campaign"
                ],
                "summary": "Get My Campaigns",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil daftar kampanye milik sendiri",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Campaign"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized: Silakan login kembali",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal mengambil data dari database",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/campaign/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memperbarui data kampanye (Judul, Deskripsi, Target, atau Banner). Hanya pemilik kampanye yang bisa melakukan update.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Campaign"
                ],
                "summary": "Update Campaign",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Kampanye",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Judul Baru",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Deskripsi Baru",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Target Dana Baru",
                        "name": "target_amount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Deadline Baru (YYYY-MM-DD)",
                        "name": "deadline",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "ID Kategori Baru",
                        "name": "campaign_category_id",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "File Banner Baru (Opsional)",
                        "name": "image_banner",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil memperbarui kampanye",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Input tidak valid",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden: Bukan pemilik kampanye",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/campaign/{slug}": {
            "get": {
                "description": "Mengambil detail lengkap satu kampanye berdasarkan Slug (URL unik).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Campaign"
                ],
                "summary": "Get Campaign Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug Kampanye (contoh: bantu-masjid-al-ikhlas)",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detail Kampanye ditemukan",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Campaign"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Kampanye tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/user/profile/beneficiaries": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil profil lengkap Penerima Manfaat. Field yang dikembalikan dinamis: jika 'individual' akan muncul NIK \u0026 data pribadi, jika 'organization' akan muncul No. Registrasi \u0026 NPWP.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get Beneficiary Profile",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil profil (Data berisi gabungan User \u0026 Profile)",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Data tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/user/profile/donors": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil data profil user yang sedang login (Donor) berdasarkan token JWT yang dikirimkan di header Authorization.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User Profile (Donor)",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil profil user",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized: Token tidak valid atau expired",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "404": {
                        "description": "User tidak ditemukan di database",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/user/profile/update-beneficiaries": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memperbarui data profil Penerima Manfaat. Menggunakan multipart/form-data untuk mendukung upload foto profil.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update Beneficiary Profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nama Lengkap",
                        "name": "full_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Nomor Telepon",
                        "name": "phone_number",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Alamat Lengkap",
                        "name": "alamat",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Deskripsi Singkat/Bio",
                        "name": "bio_description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "NIK (Jika tipe individu)",
                        "name": "nik",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Jenis Kelamin",
                        "name": "jenis_kelamin",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tempat Lahir",
                        "name": "tempat_lahir",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tanggal Lahir",
                        "name": "tanggal_lahir",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Pekerjaan",
                        "name": "pekerjaan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Nomor Registrasi (Jika tipe organisasi)",
                        "name": "registration_number",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "NPWP (Jika tipe organisasi)",
                        "name": "npwp",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "File Foto Profil (.jpg, .png)",
                        "name": "photo_profile",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Profil berhasil diperbarui",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Format data salah",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal memproses data di server",
                        "schema": {
                            "$ref": "#/definitions/model.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.APIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data sukses (opsional)"
                },
                "error": {
                    "description": "True/False",
                    "type": "boolean"
                },
                "message": {
                    "description": "Pesan untuk user",
                    "type": "string"
                },
                "type": {
                    "description": "Jenis error (ValidationError, etc)",
                    "type": "string"
                }
            }
        },
        "model.BeneficiaryProfile": {
            "type": "object",
            "properties": {
                "agama": {
                    "type": "string"
                },
                "alamat": {
                    "type": "string"
                },
                "avatar_url": {
                    "type": "string"
                },
                "beneficiary_type": {
                    "type": "string"
                },
                "bio_description": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jenis_kelamin": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "npwp": {
                    "type": "string"
                },
                "pekerjaan": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "photo_profile": {
                    "type": "string"
                },
                "registration_number": {
                    "type": "string"
                },
                "tanggal_lahir": {
                    "type": "string"
                },
                "tempat_lahir": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "model.Campaign": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "current_amount": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_banner": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "story": {
                    "description": "Field baru",
                    "type": "string"
                },
                "target_amount": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.RefreshTokenReq": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "model.RegisterBeneficiaryReq": {
            "type": "object",
            "required": [
                "profile",
                "user"
            ],
            "properties": {
                "profile": {
                    "$ref": "#/definitions/model.BeneficiaryProfile"
                },
                "user": {
                    "$ref": "#/definitions/model.User"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "beneficiary_type": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "google_uid": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "id_token": {
                    "type": "string"
                },
                "is_verified": {
                    "type": "integer"
                },
                "photo_profile": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Masukkan token dengan format: \"Bearer \u003cyour_token\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Filantropi API",
	Description:      "Backend API untuk platform filantropi.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
